ORG 0000H                        ;SET PROGRAM COUNTER AT 00H OR IONITIALIZE PROGRAM
MOV P0,#0FFH                     ;SET P0 AS INPU PORT
SETB P2.0                        ;SET PIN 28 FOR INPUT
SETB P2.1                        ;SET PIN 29 FOR INPUT
SETB P2.2                        ;SET PIN 30 FOR INPUT
MODE1 BIT 01H                    ;ASSINGNING NAME TO BIT FOR SIMPLICITY
MODE2 BIT 02H                    ;ASSINGNING NAME TO BIT FOR SIMPLICITY
KEY   BIT 03H	                 ;ASSINGNING NAME TO BIT FOR SIMPLICITY
REAPET:


				MOV A,P0                         ;SAVING DATA IN A FROM PORT 0
				MOV R0,A                         ;SAVIOND DATA IN R0 FOR SAFATE PURPOSE
				MOV C,P2.5  ;KEY                 ;TACKING INPUT OF KEY 
				MOV KEY,C                        ;MOVING KEYT SELECTION IN 20.0(BIT 1 OF RAM LOCATION 20)
				CLR C                            ;CLEARING CARRY TO AVOID ANY DATA MISMATCH
				MOV C,P2.6  ;MODE[1]             ;DECIDE WHETHRT HARDWARE DO ENCRYPTION OR DECRIPTION
				MOV MODE1,C                      ;MOVING UPPER BIT OF MODE  IN 20.1(BIT 2 OF RAM LOCATION 20)
				CLR C                            ;CLEARING CARRY TO AVOID ANY DATA MISMATCH
				MOV C,P2.7  ;MODE[2]             ;DECIDE WHETHRT HARDWARE DO ASYMMETRIC OPERATION OR SYMMMETRIC OPERATION
				MOV MODE2,C                      ;MOVING LOWER BIT OF MODE SELECTION IN 20.2(BIT 3 OF RAM LOCATION 20)
				CLR C                            ;CLEARING CARRY TO AVOID ANY DATA MISMATCH
				
					;	CLR MODE2     ;FOR MANUAL CHECKING OF CODE
					;	SETB KEY      ;FOR MANUAL CHECKING OF CODE
					;	CLR MODE1     ;FOR MANUAL CHECKING OF CODE
				
                
                JB MODE2,ASYMETRIC                  ;IS MODE 2 IS 1 THEN GOES DIRECTLY TO THE ASYMMETRIC BLOCK
				
					MOV B,#10100111B                ;KEY SET 0 IS BY DEFUALT LOADED IN R7 AS KEY
				    JNB KEY,GO1                     ;IF KEY IS 1 THEN SELECT THIS AS KEY FOR ENCRYPTION ELSE SKIOP BLOCK
						MOV B,#11001110B               
					GO1:
					
							JB MODE1,DECRIPTION1    ;IF BOTH MODE1 AND MODE2 ARE 0 THEN THIS BLOCK IS EXICUTE
							; XNORING DATA WITH KEY AND THEN ROATETING IT TO RIGHT 2 TIMES
								XRL A,B
								CPL A
								RR A
								RR A
								LJMP CRYPTED        ;AS DATA IS ENCRYPTED JUMP TO CRYPTED SO ANY OTHEN BLOCK WILL NOT EXICUTE
							
							DECRIPTION1:            ;IF BOTH MODE1 IS 1  AND  MODE2 IS 0 THEN THIS BLOCK IS EXICUTE
							 ; ROATETING DATA TO LEFT 2 TIMES AND THEN XORING WITH KEY WHICH HAS BEEN USED IN ENCRYPTION
								RL A
								RL A
								CPL A
								XRL A,B
								LJMP CRYPTED        ;AS DATA IS DECRIPTED JUMP TO CRYPTED SO ANY OTHEN BLOCK WILL NOT EXICUTE
		
		
				   ASYMETRIC:
				   ;N=256  SO PUB*PRIVATE=255(MODULE 256 HAS USED)
					       
							JB MODE1,DECRIPTION        ;IF BOTH MODE1  IS 0  AND MODE2 IS 1 THEN THIS BLOCK IS EXICUTE
								MOV B,#03D             ;KEY[0] IS BY DEFUALT LOADED IN R7 AS KEY
								JNB KEY,GO2            ;IF KEY IS 1 THEN SELECT THIS AS KEY 
								MOV B,#05D             
								GO2:
								
									MUL AB             ;MULTIPLYING DATA WITH PUBLIC KEY AND THEN DOING DEVISIOIN WITH N AND 
									                   ;STORING REMINDER IN A BUT AS HERE WE DEVIDE NUMBER WITH 256 SO REMINDER  
													   ;IS LAST 8 BIT OF MULTIPLIED DATA AND IT IS ALREADY STORED IN A SO HERE
													   ;NOT REQUIRE DO ANY OTHER OPERATION
						
								LJMP CRYPTED           ;AS DATA IS ENCRYPTED JUMP TO CRYPTED SO ANY OTHEN BLOCK WILL NOT EXICUTE
							
							DECRIPTION:                ;IF BOTH MODE1 AND MODE2 ARE 1 THEN THIS BLOCK IS EXICUTE
							  
							        MOV B,#171D        ;KEY[0] IS BY DEFUALT LOADED IN R7 AS KEY
								    JNB KEY,GO3        ; IF KEY IS 1 THEN SELECT THIS AS KEY AND NAME IT AS KEY[1]
								    MOV B,#205D             
									GO3:
									MUL AB             ;MULTIPLYING DATA WITH PRIVATE KEY AND THEN DEVIDING BY  N AND 
									                   ;STORING REMINDER IN A BUT AS HERE WE DEVIDE NUMBER WITH 256 SO REMINDER  
													   ;IS LAST 8 BIT OF MULTIPLIED DATA AND IT IS ALREADY STORED IN A SO HERE
													   ;NOT REQUIRE DO ANY OTHER OPERATION
							
                           CRYPTED:
				MOV P1,A                               ;PROVING A AS OUTPUT TO PORT 01
									

LJMP REAPET                                            ;FOR CONTINUOUS EXICUTION OF PROGRAME
END